### ISSUE TITLE
cdn.twit.tv

### ISSUE THREAD

**Issue by PDelahanty** [sethleedy/GRC-SECURITY-NOW-PODCAST-DOWNLOAD-SCRIPT#13]
All TWiT episodes have been changed to use cdn.twit.tv instead of twit.cachefly.net starting in February 2016.  I've submitted a pull request to update the code here. If it could be merged into the master, we'd appreciate it!  We use cdn.twit.tv for analytics and want to make sure Steve's show gets credit for the downloads so it can continue for years and years! :)

-Patrick Delahanty
 Web Engineer - TWiT.tv

**Comment by sethleedy** [comment]
Roger. THanks for the update.
I have been offline with TWiT for a few months. Glad to see some up interest.
