### ISSUE TITLE
Integer Expression Expected

### ISSUE THREAD

**Issue by LwsBtlr** [sethleedy/GRC-SECURITY-NOW-PODCAST-DOWNLOAD-SCRIPT#16]
created a new folder in ~/Sites/ and ran
`~/bin/grc-sn.sh -all -ahq -create-rss-audio -pd 4 `

which generated three errors:

`Users/lbutlr/bin/grc-sn.sh: line 221: [: : integer expression expected
/Users/lbutlr/bin/grc-sn.sh: line 221: [: : integer expression expected
/Users/lbutlr/bin/grc-sn.sh: line 221: [: : integer expression expected`

`bash --version
GNU bash, version 4.4.12(1)-release (x86_64-apple-darwin17.0.0)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>`

Line 221 is `if [ "$DISK_SPACE" -le "$1" ]; then` in my copy of the script. The line that defines this is `df -T` on line 217, and `df -T "pwd"` returns nothing on my computer and -T wants a type of filesystem according to the man page, not a path.

This works:

`/bin/df "``pwd``" | grep -iv "Filesystem" | awk '{print $4}'`

**Comment by LwsBtlr** [comment]
Spoke to soon, this seems to cause other issues. Still checking on solutions.

**Comment by sethleedy** [comment]
Was this on the latest version ?

Thank you for all the details.

**Comment by sethleedy** [comment]
Believed Fixed in current Development.
